name: talktoapp
description: A voice-triggered Android application that captures images and communicates with a RunPod AI service.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.4
  camera: ^0.10.4
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^0.17.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
