name: talktoapp
description: A voice-triggered Android application that captures images and communicates with a RunPod AI service.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  http: ^1.2.1
  http_parser: ^4.0.0
  provider: ^6.1.2
  whisper_flutter_new: ^1.0.1
  permission_handler: ^11.0.1
  flutter_foreground_task: ^3.10.0  # Reverted to original version
  flutter_sound: ^9.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/ggml-base.en.bin
    - assets/ggml-tiny.en-q5_1.bin
